Feature/js 520 book catalog vanilla js
saritasa-nest/camp-js-2023-violetta-klintsova pull request #1
Opened 2023-07-06 08:08 UTC by violetta-klintsova

2023-07-06 10:50 UTC, golovachev-yaroslav requested changes

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/index.html
> +
Please remove the empty line.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/index.html
> +        <div class="logo">Books app <span class="body">© 2023</span></div>
Let's use more obvious name instead of `body`. Ex. `text-body`, or something like this.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/index.html
> +        <a href="https://github.com/saritasa-nest/camp-js-2023-violetta-klintsova">GitHub</a>
Usually, if a link opens another site add `target="_blank"`. Here is optional, just FYI.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap");
Import in css stops loading bellow styles, therefore much better import fonts in `<head>`

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +  --on-surface-color: rgb(0 0 0 / 100%);
What does it mean prefix `on?` Let's avoid it.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +/* Normalize/reset some defaults */
Normalize must be as the first. Otherwise, it could be overwritten by your styles.
Let's add https://necolas.github.io/normalize.css/ here.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +
Please remove empty line.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +/* .book-group__items {
If you don't need it please remove or add a comment about why it needs.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/index.html
> +            <datalist id="search-options">
It looks strange 
![image](https://github.com/saritasa-nest/camp-js-2023-violetta-klintsova/assets/79349309/e38c67cf-0d68-4028-85d0-3987547d0f7b)
Let's use `select` tag here.

2023-07-06 10:50 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +  display: -webkit-box;
This is not a cross-platform solution. It wouldn't work in Firefox and Edge browsers. 
You can use `display: flex;`

2023-07-06 11:06 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/book-app/style.css
> +  --on-surface-color: rgb(0 0 0 / 100%);
@golovachev-yaroslav  That's google's material guideline. I like this naming approach and used it in designs.
You can read about it here https://m2.material.io/design/color/the-color-system.html#color-theme-creation:~:text=icons%2C%20appear%20in...-,%22On%22%20colors,-App%20surfaces%20use

2023-07-06 11:07 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +  --on-surface-color: rgb(0 0 0 / 100%);
Ok, this is not obvious.

2023-07-07 03:03 UTC, ShestakovaElena commented on apps/vanilla/src/pages/book-app/index.html
> +            <datalist id="search-options">
![Screenshot from 2023-07-07 10-02-28](https://github.com/saritasa-nest/camp-js-2023-violetta-klintsova/assets/59041869/a106e2fe-f40a-4bd2-8fdd-e67a2ece27f5)
And please check behavior of the field: now after selection only selected option is available

2023-07-07 03:04 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/style.css
> +  display: -webkit-box;
It seems to be working in fine in Chrome, Edge and Firefox. Not really sure what you mean by using flex...

2023-07-07 03:09 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +            <datalist id="search-options">
Changed "input" to be "select". Should I add more custom styling for options or it is fine for now? (in Figma it is not specified)

2023-07-07 03:45 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/style.css
> +/* Normalize/reset some defaults */
Moved reset to be right under root, added normalize via npm and imported at the top

2023-07-07 03:54 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +        <div class="logo">Books app <span class="body">© 2023</span></div>
Made typography classes naming to be more explicit. Will this work?

2023-07-07 03:58 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/index.html
> +            <datalist id="search-options">
Option tag should be default.

2023-07-07 04:02 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +  display: -webkit-box;
`-webkit`, `-moz`, `-ms` - are special vendor prefixes. If you use `-moz` - it allies for Firefox but not for Chrome or Edge. Prefixes are not universal.

2023-07-07 04:20 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +            <datalist id="search-options">
Then I will leave it as it is. Thanks!

2023-07-07 07:04 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/book-app/style.css
> +  display: -webkit-box;
@golovachev-yaroslav It works in all browsers https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

2023-07-07 07:06 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/book-app/style.css
> +  display: -webkit-box;
Ok

2023-07-07 08:53 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +        <div class="logo">Books app <span class="body">© 2023</span></div>
Talked to the reviewer, this issue is resolved

2023-07-07 09:02 UTC, golovachev-yaroslav approved these changes

2023-07-07 09:46 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +        <a href="_blank">GitHub</a>
Sorry, my mistake, I wanted to do the way you showed in the previous comment, but was a bit inattentive. Thank you!

2023-07-07 14:40 UTC, dbitkovski commented on apps/vanilla/src/pages/book-app/example.ts
Can we remove this empty file?

2023-07-07 14:40 UTC, dbitkovski commented on apps/vanilla/src/pages/book-app/index.html
> +    <title>Vite App</title>
Please, update the app title

2023-07-07 14:40 UTC, dbitkovski commented on apps/vanilla/src/pages/book-app/index.html
> +                <h6 class="body-sm-text book-title">Refactoring UI</h6>
How did you decide to use `h6`. Maybe `h5` or `h4` is better? 🐱

2023-07-07 14:40 UTC, dbitkovski commented on apps/vanilla/src/pages/book-app/style.css
> +  order: 1;
Maybe we can swap `.content` and `.filters`? I don't understand why do we need `order` here

2023-07-07 14:40 UTC, dbitkovski commented on apps/vanilla/src/pages/book-app/style.css
> +    order: 2;
You can use
```
.main {
  flex-direction: row-reverse
}
```
instead :)

2023-07-07 14:48 UTC, DaniilMaslovSaritasa approved these changes

2023-07-09 04:04 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/book-app/style.css
> +  margin: 8px 0 0;
I see that you are using `BEM` in some places and in some places not. Here, for example, you could name this class as `book-card__title`. While there are not strict requirements about which naming style to use, let's be consistent, choose one naming style and stick to it everywhere.

2023-07-09 04:04 UTC, panov-aleksey-saritasa commented on apps/vanilla/vite.config.ts
>          resolve(root, 'example', 'nested', 'index.html'),
Let's remove example routes

2023-07-10 02:33 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/style.css
> +  order: 1;
I explicitly specified the order for filters and content (1 and 2), to see where is what, but row-reverse from the comment below makes more sense actually, thanks! :)

2023-07-10 02:45 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +            </label>
I didn't know that it works that way. Thanks!

2023-07-10 03:06 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/style.css
> +  outline: none;
Changed its style, should be fine now

2023-07-10 03:16 UTC, violetta-klintsova commented on apps/vanilla/src/pages/book-app/index.html
> +                <h6 class="body-sm-text book-title">Refactoring UI</h6>
Thanks for pointing it out! I didn't know that it was a bad practice. Changed levels based on your remarks.

2023-07-10 03:18 UTC, violetta-klintsova commented on apps/vanilla/vite.config.ts
>          resolve(root, 'example', 'nested', 'index.html'),
But the example page is still here, I left just in case, for future reference.

2023-07-10 04:13 UTC, dbitkovski approved these changes

2023-07-10 04:25 UTC, panov-aleksey-saritasa approved these changes

2023-07-10 08:20 UTC, merged