Feature/jc 534 blackjack by dice
saritasa-nest/camp-js-2023-violetta-klintsova pull request #3
Opened 2023-07-14 03:35 UTC by violetta-klintsova

2023-07-14 10:13 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/index.html
> +      </h3>
Looks like you missed the [header level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#:~:text=Do%20not%20skip%20heading%20levels%3A%20always%20start%20from%20%3Ch1%3E%2C%20followed%20by%20%3Ch2%3E%20and%20so%20on.).

Also, I don't think it's right to use headers as a font-size setting. I mean that the rules of the game, player's name, and dice numbers are not headers, the `p` tag is more suitable for them.

2023-07-14 10:16 UTC, violetta-klintsova commented on apps/vanilla/src/pages/blackjack-by-dice/index.html
> +      </h3>
Thanks! Actually didn't think about it, because was concentrated on actual game logic more and added styles just for fun. Will correct it anyway.

2023-07-14 11:15 UTC, andrey-gazzaev requested changes
Good job👍 but please resolve comments below.

2023-07-14 11:15 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/style.css
> +  color: #242424;
Most often we use variables for font size for indents and colors. Let's add colors to the variables

2023-07-14 11:15 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/TurnResults.ts
> +}
You can use interfaces instead of classes if the entity has no internal logic

2023-07-14 11:15 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
A [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#description) could be used to store the Subscribers. This structure is more suitable for this task

2023-07-14 11:29 UTC, violetta-klintsova commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/AccumulatorResultsDisplay.ts
> +export class AccumulatorResultsDisplay implements Subscriber<number[]> {
I think it would be appropriate to leave a more specific name. Changed it to DiceStorageDisplay, as there are multiple displays in the game  :)

2023-07-15 02:46 UTC, dbitkovski commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Interfaces.ts
> +	detach(subscriber: Subscriber<T>): void;
Not a big deal but there are common names like `subscribe` / `unsubscribe`

2023-07-15 02:46 UTC, dbitkovski commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Interfaces.ts
> +	 */
Andrey means that according to jsdoc function's description goes first and then you write `@param`, `@return`, `@throw`, etc.
https://jsdoc.app/about-getting-started.html

2023-07-16 09:14 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
@dbitkovski The `Map` has methods such as `has`, `get`, `set` and `delete`. We don't need to repeat `includes` or `indexOf` every time to check if an element is included in an array. Also, judging from the implementation, we can't have some subscripts that are identical, and `Map` assumes that we won't have identical elements.

2023-07-17 00:13 UTC, dbitkovski commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
`get` and `set` are pretty useless because publisher doesn't pick one or more subscribers. As I mentioned before it iterates over all subscribers.
@violetta-klintsova  I don't mind using map but it means you either need to create an array from the result of `Map.value()` or write a method to work with `Iterator` because this is what `Map.value()` returns

2023-07-17 01:35 UTC, violetta-klintsova commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Interfaces.ts
> +	detach(subscriber: Subscriber<T>): void;
I see, thanks for noticing. I just eventually mixed up naming from two examples, yours and from Refactoring guru :)

2023-07-17 01:41 UTC, violetta-klintsova commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Player.ts
> +			}
Good point, thanks!

2023-07-17 02:33 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/Publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
Hmm. I didn't think of the `spread` operator. Indeed, `Map` is not very convenient for that. @violetta-klintsova You don't have to change the implementation.

2023-07-17 02:42 UTC, violetta-klintsova commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/AccumulatorResultsDisplay.ts
> +	}
Old syntax was just a bit more understandable for me. Refactored classes to use TS kind of syntax.

2023-07-17 05:20 UTC, andrey-gazzaev requested changes

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/PlayerResultsDisplay.ts
> +	public update(context: Player): void {
```suggestion
	/** @inheritdoc */
	public update(context: Player): void {
```

You can use `@inheritdoc` if you implement an interface method. In doing so, `@inheritdoc` inherits the entire description from the interface method.

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/TurnGenerator.ts
> +	}
The description of the constructor can most often be left unwritten.

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/style.css
> +  /* --primary-color: #c0ccff; */
Remove the dead code

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/style.css
> +  background-size: 1rem 19rem;
If you want to use relative measurement systems, you will need a base font size. As far as I can tell, you have not set it.

Can you tell me what the size would be at `1rem` or `6rem`?

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/TurnGenerator.ts
> +	/** Save the index of the current player (starts from 0). */
```suggestion
	/** Current player index. */
```

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/PlayerResultsDisplay.ts
> +		}
What happens if I want to change the name of the `winner-color` variable. Your styles will break. As long as you have a small project, you are able to remember where you need to change the code. But more often than not, in medium to large projects, this is difficult. Not to mention developers who don't know that code.

Lets say that instead of writing a value in styles, we add or remove a class. The class can be called, for example, `display-show`.

2023-07-17 05:20 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/DiceGenerator.ts
> +	}
```suggestion
	public update(context: number): void {
		this.notify({ 
		  playerIndex: context, 
		  diceResult: this.getRandomNumber(this.maxSides),
		});
	}
```

2023-07-17 07:33 UTC, dbitkovski commented on apps/vanilla/src/pages/blackjack-by-dice/scripts/AccumulatorResultsDisplay.ts
> +	}
That's truly more understandable but believe me, if your class has 10 props to initialize you won't like duplicating this in constructor :)

2023-07-17 09:01 UTC, dbitkovski approved these changes

2023-07-17 10:08 UTC, merged