Feature/jc 541 anime table angular
saritasa-nest/camp-js-2023-violetta-klintsova pull request #4
Opened 2023-07-19 10:22 UTC by violetta-klintsova

2023-07-20 04:47 UTC, dbitkovski requested changes

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/app.component.html
> +<anime-table></anime-table>
Indentation problem. Nested elements should start with tabs / spaces.

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.css
> +  margin: 50px 0;
If you need extra space within component you should use `padding`. If you position the element relative to a parent, it's a bad practise
https://wiki.saritasa.rocks/frontend/languages/css#componentselements-should-not-position-themselves

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +    class="anime-table"
If I'm not mistaken first `class` attribute won't be applied. We can't define an attribute twice.

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	public obs$: Observable<AnimeItem[]> | undefined;
Name is not meaningful. If you read this code in 2 weeks, most likely you won't understand what it is 🐱 
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	public obs$: Observable<AnimeItem[]> | undefined;
Also, we try to mark all our properties with `readonly` modifier.
There is a simple rule about how to define if a property is readonly or not: _"Will I assign a new value to this property?"_. More often props are not reassigned during the component lifetime. Especially when we're talking about streams, because a new value comes **within** the stream.

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +		this.obs$ = this.getAnimeList();
Class properties should be initialized within a constructor.

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	public constructor(private animeService: AnimeService) {}
Mark with readonly as well, it's not supposed to be reassigned. Also, check all other ts files and fixed this problem :)

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	}
If you want to keep this function we should change access modifier to `private` because other classes shouldn't access this method

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	public obs$: Observable<AnimeItem[]> | undefined;
And one more thing 🤣 
If you use a class property from template, you can use `protected`. This is a new feature from angular 15 or 16, doesn't matter. But now most of our component properties / methods marked with `protected` or `private`. FYI `private` props are not accessible from template

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/app/header/header.component.css
> +  margin-bottom: 20px;
Same as comment above, parent component should set `margin` for header

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +	private constructor(private http: HttpClient) {}
Angular doesn't care that the constructor is private but now you can't instantiate the class manually. It's better not to use any modifiers but `public` for constructor functions

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +			map((el: AnimeResponseDto<AnimeItemDto>) => el.results),
```suggestion
map(el => el.results),
```
No need to specify type for callback parameter, it's infered from `http.get` return type

2023-07-20 04:47 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +			map((items: AnimeItemDto[]) => items.map((i: AnimeItemDto) => AnimeItemMapper.fromDto(i))),
Same here

2023-07-21 01:54 UTC, dbitkovski requested changes

2023-07-21 01:54 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	protected readonly animeItemList$: Observable<AnimeItem[]> | undefined;
1) `animeList$` will be enough, I can't get what the `item` part stands for
2) I think this property cannot be `undefined`. Why did you add it?

2023-07-21 01:54 UTC, dbitkovski commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +		return `${item.id}`;
trackby function doesn't have constraints on return type so I think you can change it to `number` and don't cast a value

2023-07-21 01:54 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +		return this.http.get<AnimeResponseDto<AnimeItemDto>>(url.toString(), { headers: this.headers }).pipe(
Let's use interceptors for headers that are applied for every request
1) https://angular.io/api/common/http/HttpInterceptor#description
2) https://angular.io/guide/http-interceptor-use-cases

2023-07-21 02:02 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	protected readonly animeItemList$: Observable<AnimeItem[]> | undefined;
1. Renamed
2. Not really sure now.. works fine without it actually

2023-07-21 09:33 UTC, dbitkovski approved these changes

2023-07-21 09:33 UTC, dbitkovski commented on apps/angular/src/core/interceptors/animeService.interceptor.ts
> +export class AnimeServiceInterceptor implements HttpInterceptor {
Consider another name for this class. It's responsibility is to append api key, it has nothing to do with anime. Also, we don't use `service` for interceptors name.

2023-07-21 09:33 UTC, dbitkovski commented on apps/angular/src/core/interceptors/animeService.interceptor.ts
> +	 */
```suggestion
        /** @inheritdoc */
```
:)

If I'm not mistaken this method is documented in `HttpInterceptor` interface

2023-07-21 09:33 UTC, dbitkovski commented on apps/angular/src/core/interceptors/httpInterceptors.ts
> +/* "Barrel" of Http Interceptors */
Barrel file is usually called an `index.[js/ts]` file. It's better to remove this comment not to confuse people

2023-07-24 02:03 UTC, violetta-klintsova commented on apps/angular/src/core/interceptors/animeService.interceptor.ts
> +export class AnimeServiceInterceptor implements HttpInterceptor {
Will ApiKeyInterceptor work?

2023-07-24 02:05 UTC, violetta-klintsova commented on apps/angular/src/core/interceptors/animeService.interceptor.ts
> +	 */
Alright, thanks for pointing it out!

2023-07-24 03:47 UTC, pavel-romanov8 requested changes

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/app.component.html
> +  <anime-table class="table"></anime-table>
We can use self closing tags in such cases
```suggestion
  <anime-table class="table" />
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.spec.ts
> +		fixture.detectChanges();
If I understand it correctly, those tests were generated by default. We don't have requirements to write them since it will only take more time. I would remove them, because they are not bringing much value, but confusion to reviewers that might think you decided to write some tests by yourself

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +        {{ element.titleJpn || "Unknown" }}
We can create a custom pipe that will encapsulate the logic with "Unknown" display so we don't have to repeat ourselves

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	protected readonly animeList$: Observable<AnimeItem[]>;
Does `Item` brings any useful context to the name? In case it doesn't, the `Anime` sounds just fine to me

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	public readonly displayedColumns: string[] = ['titleEng', 'image', 'titleJpn', 'airedStartDate', 'type', 'status'];
I guess you want a static array, not dynamic
```suggestion
	public readonly displayedColumns: readonly string[] = ['titleEng', 'image', 'titleJpn', 'airedStartDate', 'type', 'status'];
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +		return this.animeService.getAnimeList();
Do we really need this 1 method wrapper? Looks like we can use the service call directly in the constructor and reduce size of the component

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	 * Returns a unique number for each table row.
If you want specifically describe return type of the function it is better to use `@returns` jsdoc syntax

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	 *  @param item Anime item.
Looks like we have some problems with indentations

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	public readonly displayedColumns: string[] = ['titleEng', 'image', 'titleJpn', 'airedStartDate', 'type', 'status'];
Since you are using `protected` for `animeList$` we can do the same thing for this class member as well
```suggestion
	protected readonly displayedColumns: string[] = ['titleEng', 'image', 'titleJpn', 'airedStartDate', 'type', 'status'];
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/animeService.interceptor.ts
> +/** Interceptor to handle authorization.  */
```suggestion
/** Interceptor to handle authorization. */
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +/** Service to get different type of anime data. */
What if I want to update the anime? The description will be misleading. I suggest not to complicate things and leave _Anime service_ instead

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor(private http: HttpClient) {}
```suggestion
	public constructor(private readonly http: HttpClient) {}
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +			map(el => el.results),
```suggestion
			map(({ result }) => results),
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on libs/core/dtos/animeItem.dto.ts
> +/** Anime list DTO. */
I guess it is not a list

2023-07-24 03:47 UTC, pavel-romanov8 commented on libs/core/dtos/animeItem.dto.ts
> +	readonly aired: {readonly start: string; readonly end: string;};
We can move it to a separate DTO/mode with the name `DateRange` which specifically represents the concept of start and end dates

2023-07-24 03:47 UTC, pavel-romanov8 commented on libs/core/dtos/animeItem.dto.ts
> +	/** Airing tart and end dates. */
By moving it to a separate model we can shorten description here to
```suggestion
	/** Airing period. */
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on libs/core/models/animeItem.ts
> +	/** ID.  */
```suggestion
	/** ID. */
```

2023-07-24 03:47 UTC, pavel-romanov8 commented on libs/core/models/animeItem.ts
> +	public readonly status: string;
In case `status` and `type` fields have finite and specific set of statuses I would recommend specifying to make our code more clear in terms of domain representation

2023-07-24 04:20 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.spec.ts
> +		fixture.detectChanges();
Okay, will do, thanks!

2023-07-24 04:31 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	protected readonly animeList$: Observable<AnimeItem[]>;
I would personally prefer to add something, because then I see that this is a "list", that is an "item" etc. :)

2023-07-24 04:38 UTC, violetta-klintsova commented on apps/angular/src/core/services/anime.service.ts
> +/** Service to get different type of anime data. */
Reasonable remark) Thanks!

2023-07-24 04:41 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	protected readonly animeList$: Observable<AnimeItem[]>;
Why does structures that we operate with somehow affect naming of domain modles? Looks like an abstraction leak to me

2023-07-24 04:50 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +		return this.animeService.getAnimeList();
In this case we could, but later with pagination this wrapper helps me a lot. So I would leave it for now

2023-07-24 05:49 UTC, violetta-klintsova commented on libs/core/models/animeItem.ts
> +	public readonly status: string;
Created separate files with enums for each of them, hope that is what you meant :)

2023-07-25 02:58 UTC, dbitkovski approved these changes

2023-07-26 02:49 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	/** Array of anime items. */
```suggestion
	/** Anime list. */
```

2023-07-26 02:49 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/animeService.interceptor.ts
> +/** Interceptor to handle api key. */
```suggestion
/** Interceptor to handle API key. */
```

2023-07-26 02:49 UTC, pavel-romanov8 commented on apps/angular/tsconfig.editor.json
> +    "types": ["jest", "node"]
Please, remove jest from types since we don't have any tests in place

2023-07-26 02:49 UTC, pavel-romanov8 commented on package.json
> +    "@types/mocha": "^10.0.1",
The same thing with test-related packages. We can delete them

2023-07-26 02:49 UTC, pavel-romanov8 commented on libs/core/utils/dateRange.ts
> +export interface DateRange {
Since you are using it only in DTO we should move it from `utils` to dtos folder and rename to `DataRangeDto`

2023-07-26 02:49 UTC, pavel-romanov8 commented on libs/core/mappers/anime.mapper.ts
> +	 * @param dto Anime list dto.
```suggestion
	 * @param dto Anime dto.
```

2023-07-26 02:49 UTC, pavel-romanov8 commented on apps/angular/src/core/utils/EmptyValuePipe.ts
> +		return value || 'Unknown';
Would be great to be more explicit in your conditions
```suggestion
		return value === '' || 'Unknown';
```

2023-07-26 02:49 UTC, pavel-romanov8 commented on libs/core/utils/typeOptions.ts
> +	Special = 'SPECIAL',
The same thing with these enums. They are not util types, but specifically related to DTO, therefore should be rename and placed in a relative folder

2023-07-26 02:49 UTC, pavel-romanov8 commented on libs/theme/src/variables.css
> +  --bottom-border-thin: 2px;
I would use `size` or `width` instead because it is hard to image how `thin` can be measured while is it pretty clear with the alternatives that I gave you
```suggestion
  --bottom-border-size: 2px;
```

2023-07-26 04:11 UTC, violetta-klintsova commented on libs/theme/src/variables.css
> +  --bottom-border-thin: 2px;
I actually don't need it, forgot to delete.

2023-07-28 12:12 UTC, pavel-romanov8 approved these changes

2023-07-28 12:12 UTC, pavel-romanov8 commented on libs/core/models/anime.ts
> +export class Anime {
Can we use simple type instead of class? There are certain problems with classes like work with utility types, serialization and overall boilerplat-ish code that make it less favourable than types. We still can use classes, but when they are really needed and it doesn't look like the case

2023-07-31 04:36 UTC, merged