Feature/jc 547 anime list management
saritasa-nest/camp-js-2023-violetta-klintsova pull request #5
Opened 2023-07-28 03:32 UTC by violetta-klintsova

2023-07-28 04:12 UTC, TienLuu-Saritasa commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +<h2 id="anime-table" class="anime-table-title">All anime</h2>
Hi, why this `h2` has `id` is `anime-table` but not `anime-table-title`
How about rename `class="anime-table-title"` to `class="title"`?

2023-07-28 04:12 UTC, TienLuu-Saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	): Observable<Pagination<Anime>> {
I think you should use an object here instead of using lots of parameters. 
Consider creating a new interface like `PaginationOption` or any names that you like. And maybe you can reuse your `QueryParameters` for this new interface

2023-07-28 04:12 UTC, TienLuu-Saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	): Observable<Pagination<Anime>> {
For example: `public getAnimeList(options: PaginationOptions): Observable<Pagination<Anime>> {`

2023-07-28 05:41 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +<h2 id="anime-table" class="anime-table-title">All anime</h2>
Hey, good point about renaming, simplified it as you suggested. Also changed `id` on `h2` to just `title`. Hope this makes a bit more sense now :)

2023-07-28 06:03 UTC, violetta-klintsova commented on apps/angular/src/core/services/anime.service.ts
> +	): Observable<Pagination<Anime>> {
Thanks, it would be a nice improvement! But not sure that `QueryParameters` interface fits here... I have made a different one for this case, hope this works as well.

2023-07-28 11:36 UTC, pavel-romanov8 requested changes

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.css
> +  background: var(--shade-color);
Prefer using background specific properties if you intended of setting only one of them. In your example it can be `background-color`. The reason is simple `background` setting a bunch of properties alongside with colors which might lead to unexpected behavior

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.css
> +  right: 0;
As a shorthand property we can use `inset`. Not sure if it fits here, just giving you an alternative

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +<h2 id="title" class="title">All anime</h2>
Are you using this `id` anywhere?

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +></camp-list-management>
Looks like we can use self-closing tag

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +    <mat-spinner></mat-spinner>
The same with self-closing tag

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	private destroy$: Subject<boolean> = new Subject<boolean>();
While this approach works ok we can use `DestroyRef` instead to avoid using `OnDestroy` explicitly as well as having separate subject for destroy actions. The general using is the following:
```ts
public constructor(
  private readonly destroyRef: DestroyRef,
) {}

// utility rx operator provided by angular
takeUntilDestroy(this.destroyRef),
```

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	private page$ = new ReplaySubject<number>(1);
Usually we can keep all observables and subject read-only

2023-07-28 11:36 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +		this.page$.next(params['page']);
The problem with current approach is multiple sources of truth. As an example: we have query params where we store page number, we have `pageIndex` variable where we store the same page index and we have page subject where we store the same page index. Would be great to somehow create only 1 source for all changes and data storage.

P.S. I'm not sure whether it is required to integrate query pagination/filters. In case it is, we can make it as a primary source of our data instead of having a lot of variables and subjects

2023-07-31 04:41 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.css
> +  right: 0;
Works fine, thanks. Didn't know that such thing exists :)

2023-07-31 04:46 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +<h2 id="title" class="title">All anime</h2>
Yes, below in `aria-describedby="title"`. Table requires some sort of description and I wanted it to be before filters, that's why I used this approach instead of a `caption`, which has to be placed next to the table.

2023-07-31 04:54 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	private destroy$: Subject<boolean> = new Subject<boolean>();
Thanks for that!

2023-07-31 12:36 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/list-management/ListManagementOptions.ts
In angular we name our files in `kebab-case` let's be consistent.

2023-07-31 12:36 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/list-management/list-management.component.html
> +        <mat-option value="UNKNOWN">Unknown</mat-option>
Currently, there is an issue with this approach. You have filters by `DistributionTypes`. You have enum for this, but here you don't rely on these values. If you add a new item to enum, there will be no new item in this select.

Let's fix it:
* We can transform enum to array (extract values of enum to an array)
* We can use [alternative approach](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAggOQJIFkCiB9AKgTQApoDKMAvDANoDkA8gGpyUA0MlWtTLKAqoUgMIdKhAnyRwAMoK4IA0gmoB1BIJR0kaSgF0YAQwgxQkKAG4AUKagBPAA4BTeGACWAW1tYb9slbsgAZvGR0bHwicjAAV2cAI1sAJ00zAHpEmFSYAD0AflMgA): instead of enums we can use unions

2023-07-31 12:36 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +			this.page$.next(this.pageIndex);
Looks like code duplication, can we extract it to a method?

2023-08-01 10:17 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +			this.page$.next(this.pageIndex);
This thing was removed due to refactoring)

2023-08-01 10:18 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime-table/list-management/list-management.component.html
> +        <mat-option value="UNKNOWN">Unknown</mat-option>
I used `ngFor` with transforming to array, as you suggested. Will this work?

2023-08-03 00:45 UTC, pavel-romanov8 approved these changes

2023-08-03 00:45 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.html
> +          {{ option | titlecase }}</mat-option
Something from with formatting here

2023-08-03 00:45 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table/anime-table.component.ts
> +	protected response$!: Observable<Pagination<Anime>>;
There is no need to do such things. We can initialize it directly in the constructor since `ActivatedRoute` is available in here

2023-08-03 01:08 UTC, dbitkovski approved these changes

2023-08-03 01:08 UTC, dbitkovski commented on libs/core/models/management-options.ts
> +	search: string;
Don't forget that we usually try to use `readonly` as much as possible to prevent unexcepted object mutations.

2023-08-03 02:48 UTC, merged