Feature/authorization jc 553
saritasa-nest/camp-js-2023-violetta-klintsova pull request #6
Opened 2023-08-07 10:33 UTC by violetta-klintsova

2023-08-10 10:08 UTC, andrey-gazzaev requested changes
Good job👍

2023-08-10 10:08 UTC, andrey-gazzaev commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +					if (refresh && e.url !== 'https://api.camp-js.saritasa.rocks/api/v1/auth/token/refresh/') {
Isn't part of that url in your env file?
```suggestion
					if (refresh && e.url !== `${this.env.ApiUrl}/auth/token/refresh/`) {
```

2023-08-10 10:08 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth-storage.service.ts
> +	}
What happens if you have to store something else other than tokens and authorization? If you extend this service, sooner or later it will become unsupported. 

Besides, what if we have to change the storage to `session storage` or it becomes external at all? Why don't we have an abstraction for that.

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.html
> +        (input)="onPasswordInput()"
We can remove handle this event if we change condition for "Confirm password" field

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.html
> +      </mat-error>
```suggestion
      <mat-error
        *ngIf="signUpForm.hasError('matchError') &&
          !signUpForm.get('confirmedPassword')?.hasError('required')">
          Passwords don't match
      </mat-error>
```

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.ts
> +	protected onPasswordInput(): void {
You can remove. See my comment above

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/header/header.component.css
> +  cursor: pointer;
Why we need this style for non active element? Maybe better to use <a> instead?

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/header/header.component.css
> +  cursor: pointer;
Please remove, it's default style

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/header/header.component.css
> +.all-anime:hover {
We don't need this style for both pseudo-classes

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/header/header.component.ts
> +	/** User authorization status. */
"True" or "false" - it is not a user status. Let's improve docs: 
```suggestion
	/** Whether user is authorized or not. */
```

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/header/header.component.ts
> +				this.changeDetector.markForCheck();
Do we really need this mark?

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/landing/landing.component.html
> +	</div>
For link we must use <a>.

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/landing/landing.component.html
> +    <img src="../../assets/spirited-away.jpg" alt="" />
Please add text for "alt" attribute to improve accessibility

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on apps/angular/src/core/utils/equal-passwords-validator.ts
> + * Checks whether two passwords are equal.
Let's improve docs => we don't have two passwords

2023-08-10 12:54 UTC, irina-baleevskih-saritasa commented on libs/core/dtos/registration-info.dto.ts
> +	/** Lst name. */
typo 
```suggestion
	/** Last name. */
```

2023-08-11 04:29 UTC, violetta-klintsova commented on apps/angular/src/app/header/header.component.ts
> +				this.changeDetector.markForCheck();
Probably not anymore, as I did some refactoring and now it works a bit different. I will remove it)

2023-08-11 04:31 UTC, violetta-klintsova commented on apps/angular/src/app/header/header.component.ts
> +				this.changeDetector.markForCheck();
Yeah, I guess we do, otherwise header component will not rerender after we get user profile and log in

2023-08-11 04:38 UTC, violetta-klintsova commented on apps/angular/src/app/features/auth/log-in/log-in.component.css
> +  background-color: #ff689a;
I now have a bit of a mixup with material default colors and colors I would like everything to stick to. I will add the varible for now, but maybe later redo it (if the time allows) :) Thanks!

2023-08-11 04:39 UTC, irina-baleevskih-saritasa commented on apps/angular/src/app/header/header.component.ts
> +				this.changeDetector.markForCheck();
If you worry about  "isLoggedIn" checking in template - component will re-render after get new value

2023-08-11 04:52 UTC, violetta-klintsova commented on apps/angular/src/app/header/header.component.css
> +  cursor: pointer;
Changed it to be a link

2023-08-14 09:22 UTC, andrey-gazzaev approved these changes

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/app/app-routing.module.ts
> +	},
Do I understand correctly that when authorizing, you can still get to the authorization page?

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.html
> +      }}</mat-error>
What if you have 20 conditions to validate? Would you write them all?

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/app/header/header.component.html
> +    </button>
These buttons look like links. From a semantic point of view, using the `button` tag is not correct

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/app/landing/landing.component.html
> +		<a class="all-anime-link" [routerLink]="isLoggedIn ? ['/anime'] : ['/auth/log-in']">All anime</a>
You can configure `guard` to redirect to the login page if the user is not authorized

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth.service.ts
> +		const mappedRegisterData = RegistrationInfoMapper.toDto(registerInfo);
```suggestion
		const mappedRegister = RegistrationInfoMapper.toDto(registerInfo);
```

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth.service.ts
> +		const url = new URL(path, this.apiUrl);
```suggestion
		const url = new URL('auth/register/', this.apiUrl);
```

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth.service.ts
> +		this.tokenService.setToken('refresh', refresh);
Would you like to concatenate these two tokens into a single data structure? From my point of view the tokens are logically identical

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/core/services/token-service.service.ts
> +	}
Why pass a token `key` to this method? The key can be stored directly in the service.

2023-08-14 09:22 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.html
> +    (click)="onSubmit()"
The form has a `submit` handler

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on apps/angular/src/core/services/token-service.service.ts
> +@Injectable({
This is storage or token service? Let's improve docs

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on apps/angular/src/core/services/token-service.service.ts
> +	 * Return an token.
```suggestion
	 * Return a token.
```

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on apps/angular/src/core/services/token-service.service.ts
> +	 * Saves an item in the storage.
```suggestion
	 * Saves the token in the storage.
```

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on libs/core/dtos/error-response.dto.ts
> +export interface ErrorResponse {
```suggestion
export interface ErrorResponseDto {
```

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on libs/core/mappers/error-response.mapper.ts
> +	 * @param dto Genre dto.
Typo?

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on libs/core/mappers/user-profile.mapper.ts
> +	 * @param resultsMapper Mapper for results property.
```suggestion
```

2023-08-14 09:22 UTC, irina-baleevskih-saritasa commented on libs/core/models/user-profile.ts
> +	readonly created: string;
It doesn't convenient for us to store and handle the date in "string" format. Try now to display the date for example. We usually map the date to the Date class. Or, if you don't use this field, you can omit it in model
```suggestion
	readonly created: Date;
```

2023-08-14 09:26 UTC, violetta-klintsova commented on libs/core/mappers/error-response.mapper.ts
> +	 * @param dto Genre dto.
Copy/paste type, sorry

2023-08-14 09:35 UTC, violetta-klintsova commented on libs/core/models/user-profile.ts
> +	readonly created: string;
I don't need the user for now at all, I created a model and a mapper just for consistency (maybe it is not right), so that I wouldn't return DTO from the method.

2023-08-14 09:37 UTC, violetta-klintsova commented on libs/core/models/user-profile.ts
> +	readonly created: string;
Would it be okay if I added conversion to date to the mapper?

2023-08-14 09:57 UTC, irina-baleevskih-saritasa commented on libs/core/models/user-profile.ts
> +	readonly created: string;
Better not to add unused entities

2023-08-14 10:03 UTC, andrey-gazzaev commented on apps/angular/src/core/services/token-service.service.ts
> +	}
take a look at the comment above https://github.com/saritasa-nest/camp-js-2023-violetta-klintsova/pull/6#discussion_r1293210805

2023-08-15 02:33 UTC, dbitkovski requested changes

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/app/features/auth/log-in/log-in.component.ts
> +					return throwError(() => new Error('No active account with given credentials was found.'));
What is the point of throwing error here? We throw an error when we expect that someone will handle it. In this particular case we're already in component and a component is a last place where we can handle an error.

`catchError` requires to return an observable from a passed callback. If we handle an error and we want to close a stream, we can return `EMPTY`. `EMPTY` is an observable that completes immediately.

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/app/header/header.component.ts
> +			});
Try to work with observables. If you make `isLoggedIn` property an observable and use `async` pipe on the template, you won't need to call `markForCheck` manually. And your code will become much simplier :)

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/assets/spirited-away.jpg
❤️

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/interceptors/auth.interceptor.ts
> +		if (!token) {
There are endpoints which we don't want to append a token for. For example, login or sign up. Ideally you're not able to access this page if you're authorized but to prevent unexcepted issues it's better to add one more check here.

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +				if (request.context.get(BYPASS_LOG) === true) {
Never saw this 😨 
That's an interesting solution but has one big problem: your services know about some misterious interceptors and how to avoid them :)
Usually, when we want to ignore interceptor logic, we write a custom boolean method that determines if we need to modify request or by pass it.

So instead of `request.context.get(BYPASS_LOG) === true)` you'll have something like `shouldUrlBeHandled`.
That's totally fine that an interceptor has information about URLs, it's responsible for handling requests so we consider it to have such permissions.

Anyway, your solution with context is great. Never thought about it in this context :)

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +						return this.auth.refreshToken(refresh).pipe(
Imagine your app is making two request at the same time and both fail because access token is expired. Right now your code makes 2 request to refresh token which is incorrect.
Come up with a solution when we don't make a new request if there is an active one already.

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +	public setUser(access: string, refresh: string): void {
I see you call this method from the 3 different places (login, signup, refresh interceptor). Do you think it's convenient API? I mean let's imagine that I work with you on this project and I call `login` method. I expect that this method literally logs me in but instead it returns some tokens that I should somehow handle...
I believe we don't need to expose tokens this way and simply makes this method `private`. Then you can use `tap` operator in `login`, `register` and `refreshToken` methods to call this method and save required data

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +	}
Can you explain what is the point of this method? :)
Every time `userState$` is called your create a new observable based on `userStateSubject$` subject which makes no sense at all.
I don't think we want class clients to get new observable every time but instead work with the one instance.
Change it to `public readonly userState$ = this.userStateSubject$.asObservable()`, that's enough

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +						return throwError(() => ErrorMapper.fromDto(e.error));
Same here about using `throwError` function. Check all other places where you do that and replace with `throw` javascript operator

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/utils/equal-passwords-validator.ts
> +		if (valueOne !== null && valueTwo !== null && valueOne.value !== valueTwo.value) {
I think if `valueOne` or `valueTwo` is missing we should throw an error because it's unexpected behavior

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/utils/equal-passwords-validator.ts
> + * @returns
Remove `@returns` tag if you don't use it

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/utils/equal-passwords-validator.ts
> +			control.get('confirmedPassword')?.setErrors({ matchError: true });
You already pass control names to the function, why do you use hardcoded names?

2023-08-15 02:33 UTC, dbitkovski commented on apps/angular/src/core/utils/equal-passwords-validator.ts
> +		const valueTwo = control.get(controlTwo);
I believe we can improve naming :)
`controlOne` and `controlTwo` are useless and don't provide any context.
- First of all, `controlOne` and `controlTwo` are names and now it's not obvious
- `controlOne` is a name of main control, it's a source of truth because we compare the value of the second control with it.
- `controlTwo` is the name of the control whose value must match the value of the first control.

Same thing about `valueOne` and `valueTwo`. To be honest, there are not values, they're controls 🤣

2023-08-15 03:47 UTC, violetta-klintsova commented on apps/angular/src/core/services/auth.service.ts
> +						return throwError(() => ErrorMapper.fromDto(e.error));
I removed it from most of the files where it occurred and left one in 'refresh interceptor', because I'm not sure if there is any other way to do it

2023-08-16 02:53 UTC, pavel-romanov8 requested changes

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/app.component.ts
> +	/** Component initialization. */
Since `ngOnInit` is declared on `OnInit` interface we can leave `@inheritdoc` and avoid providing the same documentation for each lifecycle hook implementation

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/app.component.ts
> +					this.auth.removeUser();
Do you really want to have this flow? What if there is some internal service error and we get 500-ish status code?

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/app.component.ts
> +			.subscribe(() => this.auth.updateUserState(true));
Please, don't forget to manage subscriptions properly. With current implementation you subscribed (created subscription), but it won't be cleared automatically

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/app.component.ts
> +		this.auth
Could you please provide me some info on why do we have such logic in component? It looks like component doing user authorization and handling all results of it which is not quite the thing we want to have on UI layer

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/app-routing.module.ts
> +				canMatch: [modulesGuard],
Basically, modules guard it is the same authorization guard, but it only allows to proceed in case user is logged in. I would rename both of the guard to make it easier to understand your intentions. Modules guard can be named as `authorizedGuard` and `authGuard` as `unauthorizedGuard`

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +            <img src="{{ element.image }}" alt="Anime image" />
This `alt` doesn't provide much values it would be the same for every image. If you want to make useful `alt` text we can use something like this `Cover of ${anime.titleEng}`. That way each cover is different for each anime item and provides more comprehensive information

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/log-in/log-in.component.css
> +  color: white;
Don't you have a variable fro the white color?

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/log-in/log-in.component.ts
> +	protected loginForm: FormGroup;
Looks like we are not mutating `logingForm` field and can make it read-only
```suggestion
	protected readonly loginForm: FormGroup;
```

2023-08-16 02:53 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/log-in/log-in.component.ts
> +	protected isDisabled = false;
It seems that you are not using this field and it can be deleted

2023-08-16 03:45 UTC, violetta-klintsova commented on apps/angular/src/app/app-routing.module.ts
> +	imports: [RouterModule.forRoot(routes, { enableTracing: false })],
I was playing around with routes and forgot to remove it

2023-08-16 03:47 UTC, violetta-klintsova commented on apps/angular/src/app/app.component.ts
> +	/** Component initialization. */
In the next PR I fixed it in all components, can I set this comment in resolved? Or should I add changes here as well?

2023-08-16 04:57 UTC, violetta-klintsova commented on apps/angular/src/app/app.component.ts
> +					this.auth.removeUser();
Well, I made some changes, but I am not realy sure if I am on the right track.

2023-08-16 05:01 UTC, violetta-klintsova commented on apps/angular/src/app/app.component.ts
> +		this.auth
I moved the handling to the service itself, but still have to call the method in the App component. 
Actual user profile data is not needed for now, I just have to update the userState(which is a boolean) in case of success.

2023-08-16 05:03 UTC, violetta-klintsova commented on apps/angular/src/app/app.component.ts
> +				this.auth.logIn(access, refresh);
This is the old code, I refactored it.

2023-08-16 05:03 UTC, violetta-klintsova commented on apps/angular/src/app/app.component.ts
> +		const refresh = this.storage.getRefreshToken();
Same here, outdated.

2023-08-17 09:42 UTC, dbitkovski requested changes

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.ts
> +	public isLoading = false;
I believe it also should be `protected`

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/app/features/auth/sign-up/sign-up.component.ts
> +	protected signUpForm: FormGroup;
And this one `readonly` since you don't assign any other values

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/app/header/header.component.ts
> +	public onLogOut(): void {
Change to `protected` and check all other properties / methods that are called from the same class or component's template

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/app/landing/landing.component.html
> +    <button
You have `routerLink`, why is it a `button` and not an `a`?

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +	private userStateSubject$ = new ReplaySubject<boolean>(1);
Same as `protected`. Apply `readonly` to all properties that are not supposed to be reassigned

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +	public updateUserState(value: boolean): void {
Can we make it private? I don't think something else can change user state without calling appropartiate methols like `login`, `signup`, etc.

2023-08-17 09:42 UTC, dbitkovski commented on apps/angular/src/core/services/storage.service.ts
> +		window.localStorage.setItem(key, value);
Please, don't use global variables. If you want to achive `window` object, it's better to create a DI token and then provide `window` via this token.

2023-08-18 04:32 UTC, dbitkovski approved these changes

2023-08-18 04:32 UTC, dbitkovski commented on .eslintrc.json
> +        "import/order": ["error", {
Indentation problem. This line uses spaces instead of tabs

2023-08-21 10:59 UTC, pavelzadorin-saritasa approved these changes

2023-08-21 10:59 UTC, pavelzadorin-saritasa commented on libs/core/dtos/anime-details.dto.ts
> +export interface AnimeDetailsDto {
It seems to me that you can inherit this DTO from `AnimeDto` so as not to duplicate common properties.

2023-08-21 10:59 UTC, pavelzadorin-saritasa commented on libs/core/mappers/anime-details.mapper.ts
> +			titleEng: dto.title_eng,
You can re-use `AnimeMapper` for common properties.

2023-08-23 05:12 UTC, merged