Feature/jc 559 selected anime details
saritasa-nest/camp-js-2023-violetta-klintsova pull request #7
Opened 2023-08-09 06:07 UTC by violetta-klintsova

2023-08-09 06:34 UTC, dmitrymaslov13 requested changes

2023-08-09 06:34 UTC, dmitrymaslov13 commented on libs/core/models/anime-details.ts
> +	id: number;
please don't forget about readonly

2023-08-09 06:34 UTC, dmitrymaslov13 commented on libs/core/models/anime-details.ts
> +	genres: Genre[];
And about array `readonly`

```suggestion
	readonly studios: readonly Studio[];

	/** List of genres. */
	readonly genres: readonly Genre[];
```

2023-08-09 06:34 UTC, dmitrymaslov13 commented on libs/core/mappers/date.mapper.ts
> +		return data === null ? data : new Date(data);
By your function types `fromDto(data: string)` `data` not can be `null`

2023-08-09 06:34 UTC, dmitrymaslov13 commented on libs/core/dtos/genre.dto.ts
> +	readonly type: 'GENRES' | 'EXPLICIT_GENRES' | ' THEMES' | 'DEMOGRAPHICS';
Hmm, i see you use enгms in other cases. But in this they preferred unions.

I propose to follow the approach that was chosen before, this will allow the code to be more predictable

2023-08-09 06:34 UTC, dmitrymaslov13 commented on libs/core/dtos/broadcast-day.dto.ts
> +export type BroadcastDayDto = 1 | 2 | 3 | 4 | 5 | 6 | 7;
Also about union and enums

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/index.html
> +    <script src="https://www.youtube.com/iframe_api"></script>
Do you really need this script on all pages?

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/not-found/not-found.component.ts
> +	}
-2 seems like a magic number in this case. Let's denote what it means by a variable, or add a comment ( variable is preferred )

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/not-found/not-found.component.html
> +	<a (click)="goBack()" class="back-link">Go back to the previous page...</a>
We have article about template callbacks in our wiki

https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#event-handlers

it's not essential, but it would be cool to stick to it

2023-08-09 06:34 UTC, dmitrymaslov13 commented on libs/core/models/anime-details.ts
> +export interface AnimeDetails {
Hmm, i see you have Anime class and this interface can be a class that extends it. Let's remove code duplication and inherit from anime in this case

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	protected response$: Observable<AnimeDetails>;
it looks like a server abstraction leak in the components.

the name response automatically hints that it has something to do with the server model, but in this case it does not make any sense.

we can rename it to `animeDetails$`, in the reactive model it is

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		);
let's move stream creation to separate method for a cleaner look of the constructor.

`createAnimeDetailsStream(): Observable<AnimeDetails> {...}`

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +	public getAnimeDetails(id: string): Observable<AnimeDetails> {
```suggestion
	public getAnimeDetails(id: Anime['id']): Observable<AnimeDetails> {
```

2023-08-09 06:34 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +				if (id !== null) {
in this case, the id may not be a number at all if we pass an incorrect string in the parameters, but we will still send the request.

I propose to add a check if the id is a number

2023-08-09 07:00 UTC, violetta-klintsova commented on apps/angular/src/index.html
> +    <script src="https://www.youtube.com/iframe_api"></script>
Removed it from index.html and placed in anime-details component instead, will it work? :)

2023-08-09 09:11 UTC, violetta-klintsova commented on apps/angular/src/index.html
> +    <script src="https://www.youtube.com/iframe_api"></script>
Seems like I did something similar (found [here](https://github.com/angular/components/blob/main/src/youtube-player/README.md)) but in `ngOnInit` hook

2023-08-10 13:14 UTC, danilkukryakov requested changes

2023-08-10 13:14 UTC, danilkukryakov commented on libs/core/models/anime-details.ts
> +	readonly trailer: string;
'trailer' doesn't seem like a descriptive property to me. Is it a link, some description or even id?
Please adjust the name for 'trailer' property.
I guess we can rename it like this:
```suggestion
	/** Youtube trailer ID. */
	readonly youtubeTrailerId: string;
```

2023-08-10 13:14 UTC, danilkukryakov commented on libs/core/models/anime.ts
> +	readonly image: string;
Please provide some details about this image string. Is a link or 'base64' string of the image, or maybe it's something else?
For example you can rename it like this:
```suggestion
	readonly thumbnailUrl: string;
```

2023-08-10 13:14 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +        </div>
In modern browsers we can use `<dialog>` element.
It provides better accessibility and UX. Besides, it's more semantically correct to use such element.
You can find more details about it here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog.
By the way, you can use Dialog [component](https://material.angular.io/components/dialog/overview) from Angular Material. It also has good accessibility and UX.

Note about accessibility to clarify what I mean. Usually 'accessibility' is a set of things to help user to interact with our app, e.g. using keyboard or other inputs. In dialogs/popup there is a cool feature which improves UX - close on Esc key.

2023-08-10 13:14 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +          <div class="open-full-size" (click)="changePopupState()">
It's better to avoid 'click' handlers for 'div' elements as they are not accessible. For instance, we can't access this element using Tab key.
Usually we use `<button>` to handle clicks. `<button>` element has good accessibility and it's more semantically correct to use click handler on it instead of 'div'.

2023-08-10 13:14 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +            <div>{{ details.source | titlecase }}</div>
We can do the same thing using CSS.
Check 'text-transform' property ([docs](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform)).
It's optional, btw. Solution with pipe also looks fine to me.

2023-08-10 13:38 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.css
> +.open-pop-up {
```suggestion
.opened-pop-up {
```
I think for class names it is will be more clear.

2023-08-10 13:38 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +	protected anime$: Observable<Pagination<Anime>>;
Add readonly please

2023-08-10 13:38 UTC, kristinaSvobodinaSaritasa commented on libs/core/dtos/anime-details.dto.ts
> +	readonly broadcast_day: BroadcastDayDto;
It seems that you don't use all fields, in this case there isn't need to add them to model and especially to create enum for dto value, if we don't need it.

2023-08-10 13:38 UTC, kristinaSvobodinaSaritasa commented on libs/core/mappers/date.mapper.ts
> +		return new Date(date);
```suggestion
	 return date ? new Date(date) : null;
```

2023-08-11 09:07 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +            <div>{{ details.source | titlecase }}</div>
Alright, thanks for mentioning, I though pipe in this case would be a bit more concise

2023-08-11 10:28 UTC, violetta-klintsova commented on libs/core/dtos/date-range.dto.ts
> +	readonly start: string | null;
Thanks for mentioning!

2023-08-11 10:50 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +          <div class="open-full-size" (click)="changePopupState()">
What if I already fixed it doing the next feature? Should I add changes here as well?

2023-08-14 01:21 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	}
I shall probably remove this functionality for now, as I am not sure yet how to properly implement.

2023-08-14 01:36 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	}
I moved it to the app component, seems to be enough for now)

2023-08-14 02:35 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/landing/landing.component.ts
>  			.subscribe(value => {
Can we put it inside `OnInit` method, to [avoid subscription inside a constructor](https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices#do-not-subscribe-inside-a-constructor)?

2023-08-14 03:19 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.css
> +tr.selected-row:hover {
I used class with tag selector, unfortunately only with the class selector it doesn't work

2023-08-14 03:23 UTC, violetta-klintsova commented on apps/angular/src/app/landing/landing.component.ts
>  			.subscribe(value => {
Thanks, good point) Moved it to the hook

2023-08-14 03:48 UTC, violetta-klintsova commented on apps/angular/src/app/not-found/not-found.component.ts
> +	}
I asked Dima about my idea and he said that you rarely do such stuff and recommended to simply redirect to the main page. I guess it would be better to follow this suggestion  :)

2023-08-14 03:52 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	}
I decided to remove this feature, at first it seemed nice to have it, but now I guess it is too much)

2023-08-15 11:35 UTC, danilkukryakov requested changes

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		return `(${date})`;
Such code doesn't help us to get the format of date at first glance.
Besides, current implementation has some edge cases which are not handled properly. For instance, imagine a case when we don't have startDate but have endDate (according to type definitions it's possible). We will have something like '- 2023' as a result which is strange, in my opinion.

I suppose, simple `if` statements should work fine here. It will make code more readable:
```ts
const start = startDate ? startDate.getFullYear() : null;
const end = endDate ? endDate.getFullYear() : null;

if (start != null && end != null) {
	return `(${start} - ${end})`;
}

if (start != null) {
	return `(${start})`;
}

return '-';
```

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +	protected getDateRange(startDate: Date | null, endDate: Date | null): string {
Maybe rename this method to `getYearsRange` to be clear.

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		public readonly dialog: MatDialog,
There is no need to make this property 'public'. We can make it `private`:
```suggestion
		private readonly dialog: MatDialog,
```

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +          <img src="{{ details.thumbnailUrl }}" alt="Anime cover" />
```suggestion
          <img [src]="details.thumbnailUrl" alt="Anime cover" />
```

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +        videoId="{{ details.youtubeTrailerId }}"
```suggestion
        [videoId]="details.youtubeTrailerId"
```

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +            <img src="{{ element.thumbnailUrl }}" alt="" />
```suggestion
            <img [src]="element.thumbnailUrl" alt="Anime thumbnail" />
```

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +          <img src="{{ details.thumbnailUrl }}" alt="Anime cover" />
It's not related to 'img' but since we ofter work with resource URLs in our app you have to be aware of security concerns.
Angular has a good [guide](https://angular.io/guide/security#security) on this topic in their docs. So be sure to read it.
As far as I can see there are no security issues in your code so far. So my comment is rather a tip for you to learn this topics. You may mark my comment as 'Resolved'.

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.css
> +img {
Please, avoid tag selectors if possible. Prefer CSS class selector instead.

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/app.component.ts
> +		}
Let's move this code to a private function. By the way, usually we try to keep 'ngOnInit' as small as possible.
You can adjust your code to make 'ngOnInit' smaller:
```ts
public ngOnInit(): void {
  this.fetchUserProfile();
  this.loadYoutubeAPI();
}

private fetchUserProfile(): void {
  this.auth.fetchUserProfile().pipe(/* ... */).subscribe(/* ... */);
}

private loadYoutubeAPI(): void {
  // ...
}
```

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/app.component.ts
> +		if (!youtubeApiLoaded) {
'AppComponent' is a root component in our app. So it's not possible that 'ngOnInit' function will be called twice.
I mean, 'youtubeApiLoaded' flag is redundant as this code will be executed once anyway.
Let's remove 'if' statement with 'youtubeApiLoaded' variable.

2023-08-15 11:35 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
>  			}),
Small tip about loading.
Be careful with 'tap' at the end of the pipe. If API request returns error then 'tap' will be skipped. So user will see infinite loading. To avoid this we have to set 'isLoading' to 'false' after switchMap in any case to avoid infinite loading.
You can create a custom RxJS operator to achieve this. It may look like this:
```ts
export function onMessageOrFailed<T>(callback: () => void): MonoTypeOperatorFunction<T> {
  return pipe(
    tap({
       next: callback,
       error: callback,
    }),
  );
}
```

We can use it like this:
```ts
return this.activatedRoute.queryParamMap.pipe(
  // ...
  switchMap(params => /* ... */),
  onMessageOrFailed(() => { this.isLoading = false; })
)
```

2023-08-16 02:21 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +          <img src="{{ details.thumbnailUrl }}" alt="Anime cover" />
Thanks! Will defenitely check this out :)

2023-08-16 02:31 UTC, violetta-klintsova commented on apps/angular/src/app/app.component.ts
> +		}
Thank you very much!

2023-08-16 03:37 UTC, violetta-klintsova commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
>  			}),
This moment when you wanted to do something nice in UI but it happened to be more complex than expected...)) Thanks for your tip and code suggestion! So do I unserstand it correcly, when this custom operator is used, the callback (in our case just `this.isLoading = false` ) will get executed in both cases (successful request and possible error)?

2023-08-16 04:32 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
>  			}),
Yes, your guess is correct. Callback will be executed in both cases (success and error).

2023-08-17 04:19 UTC, danilkukryakov approved these changes

2023-08-18 04:51 UTC, dbitkovski approved these changes

2023-08-18 04:51 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.html
> +            <span *ngFor="let studio of details.studios" class="studio">
Please, add `trackBy` function for this `ngFor` and one below

2023-08-20 16:35 UTC, gevorg-gevorgyan-saritasa approved these changes

2023-08-20 18:43 UTC, dmitrymaslov13 approved these changes

2023-08-21 01:30 UTC, kristinaSvobodinaSaritasa approved these changes

2023-08-21 02:03 UTC, merged